// Copyright 2023 The LevelDBWasb Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file. See the AUTHORS file for names of contributors.

// It seems WebIDL Binder recommends a single `.idl`, output file, etc.

interface Status {
  void Status();
  boolean ok();
  // Returns null if ok() is true.
  [Const] DOMString toErrorString();
};

interface Iterator {
  boolean valid();
  void seekToFirst();
  void seekToLast();
  void seek(DOMString target);
  [Const] DOMString key();
  [Const] DOMString value();
  void next();
  void prev();
  [Ref, Const] Status status();
};

interface DbWrapper {
  void DbWrapper(DOMString name);

  void put(DOMString k, DOMString v);

  void batchStart();

  void batchEnd();

  void batchPut(DOMString k, DOMString v);

  void remove(DOMString k);

  [Const] DOMString get(DOMString k);

  Iterator newIterator();

  [Ref, Const] Status getLastStatus();
};
